@echo off
echo Creando entorno virtual...
python -m venv venv

echo Cambiando al directorio del proyecto...
cd emergency_system

echo Activando entorno virtual...
call ..\venv\Scripts\activate

echo Instalando dependencias...
pip install -r requirements.txt

echo Ejecutando migraciones...
python manage.py migrate

echo Poblando base de datos...
python scripts/populate_real_data.py

echo Creando emergencias de prueba...
python manage.py seed_emergencies --with-vehicles

echo Ejecutando el sistema...
python manage.py runserver

pause