# Generated by Django 5.2.5 on 2025-08-28 18:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Force',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('contact_info', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('current_lat', models.FloatField(blank=True, null=True)),
                ('current_lon', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('available', 'Available'), ('en_route', 'En Route'), ('busy', 'Busy')], default='available', max_length=50)),
                ('force', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.force')),
            ],
        ),
        migrations.CreateModel(
            name='Emergency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, choices=[('rojo', 'Rojo - Critica'), ('amarillo', 'Amarillo - Urgente'), ('verde', 'Verde - Leve')], max_length=50)),
                ('priority', models.IntegerField(default=0)),
                ('description', models.TextField()),
                ('location_lat', models.FloatField()),
                ('location_lon', models.FloatField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('assigned', 'Assigned'), ('resolved', 'Resolved')], default='pending', max_length=50)),
                ('reported_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.vehicle')),
            ],
        ),
    ]
