# Generated by Django 5.2.5 on 2025-08-28 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergency',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='emergency',
            name='assigned_force',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.force'),
        ),
        migrations.AddField(
            model_name='emergency',
            name='onda_verde',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='emergency',
            name='code',
            field=models.CharField(blank=True, choices=[('rojo', 'Rojo - Crítica'), ('amarillo', 'Amarillo - Urgente'), ('verde', 'Verde - Leve')], max_length=50),
        ),
        migrations.AlterField(
            model_name='emergency',
            name='location_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='emergency',
            name='location_lon',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='emergency',
            name='status',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('asignada', 'Asignada'), ('resuelta', 'Resuelta')], default='pendiente', max_length=50),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='status',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('en_ruta', 'En Ruta'), ('ocupado', 'Ocupado')], default='disponible', max_length=50),
        ),
    ]
