# Generated by Django 5.2.5 on 2025-08-28 18:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_emergency_address_emergency_assigned_force_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emergency',
            options={'verbose_name': 'Emergencia', 'verbose_name_plural': 'Emergencias'},
        ),
        migrations.AlterModelOptions(
            name='force',
            options={'verbose_name': 'Fuerza', 'verbose_name_plural': 'Fuerzas'},
        ),
        migrations.AlterModelOptions(
            name='vehicle',
            options={'verbose_name': 'Vehículo', 'verbose_name_plural': 'Vehículos'},
        ),
        migrations.AddField(
            model_name='emergency',
            name='resolution_notes',
            field=models.TextField(blank=True, verbose_name='Notas de Resolución'),
        ),
        migrations.AlterField(
            model_name='emergency',
            name='address',
            field=models.CharField(blank=True, max_length=255, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='emergency',
            name='assigned_force',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.force', verbose_name='Fuerza Asignada'),
        ),
        migrations.AlterField(
            model_name='emergency',
            name='assigned_vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.vehicle', verbose_name='Vehículo Asignado'),
        ),
        migrations.AlterField(
            model_name='emergency',
            name='code',
            field=models.CharField(blank=True, choices=[('rojo', 'Rojo - Crítica'), ('amarillo', 'Amarillo - Urgente'), ('verde', 'Verde - Leve')], max_length=50, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='emergency',
            name='description',
            field=models.TextField(verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='emergency',
            name='location_lat',
            field=models.FloatField(blank=True, null=True, verbose_name='Latitud'),
        ),
        migrations.AlterField(
            model_name='emergency',
            name='location_lon',
            field=models.FloatField(blank=True, null=True, verbose_name='Longitud'),
        ),
        migrations.AlterField(
            model_name='emergency',
            name='onda_verde',
            field=models.BooleanField(default=False, verbose_name='Onda Verde'),
        ),
        migrations.AlterField(
            model_name='emergency',
            name='priority',
            field=models.IntegerField(default=0, verbose_name='Prioridad'),
        ),
        migrations.AlterField(
            model_name='emergency',
            name='reported_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Reportado en'),
        ),
        migrations.AlterField(
            model_name='emergency',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Resuelto en'),
        ),
        migrations.AlterField(
            model_name='emergency',
            name='status',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('asignada', 'Asignada'), ('resuelta', 'Resuelta')], default='pendiente', max_length=50, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='force',
            name='contact_info',
            field=models.TextField(blank=True, verbose_name='Información de Contacto'),
        ),
        migrations.AlterField(
            model_name='force',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creado en'),
        ),
        migrations.AlterField(
            model_name='force',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='current_lat',
            field=models.FloatField(blank=True, null=True, verbose_name='Latitud Actual'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='current_lon',
            field=models.FloatField(blank=True, null=True, verbose_name='Longitud Actual'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='force',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.force', verbose_name='Fuerza'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='status',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('en_ruta', 'En Ruta'), ('ocupado', 'Ocupado')], default='disponible', max_length=50, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='type',
            field=models.CharField(max_length=100, verbose_name='Tipo'),
        ),
    ]
