# Generated by Django 5.2.5 on 2025-08-28 21:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_emergency_options_alter_force_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyDispatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('despachado', 'Despachado'), ('en_ruta', 'En ruta'), ('en_escena', 'En escena'), ('finalizado', 'Finalizado')], default='despachado', max_length=20, verbose_name='Estado')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creado en')),
                ('emergency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispatches', to='core.emergency', verbose_name='Emergencia')),
                ('force', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.force', verbose_name='Fuerza')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.vehicle', verbose_name='Vehículo')),
            ],
            options={
                'verbose_name': 'Despacho',
                'verbose_name_plural': 'Despachos',
            },
        ),
    ]
