# Generated by Django 5.2.5 on 2025-08-29 10:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_emergencydispatch'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Dirección')),
                ('total_beds', models.PositiveIntegerField(default=0, verbose_name='Camas Totales')),
                ('occupied_beds', models.PositiveIntegerField(default=0, verbose_name='Camas Ocupadas')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creado en')),
            ],
            options={
                'verbose_name': 'Hospital',
                'verbose_name_plural': 'Hospitales',
            },
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Nombre y Apellido')),
                ('role', models.CharField(blank=True, max_length=100, verbose_name='Rol/Cargo')),
                ('status', models.CharField(choices=[('disponible', 'Disponible'), ('en_ruta', 'En Ruta'), ('en_escena', 'En Escena'), ('ocupado', 'Ocupado'), ('fuera_servicio', 'Fuera de Servicio')], default='disponible', max_length=20, verbose_name='Estado')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creado en')),
                ('assigned_vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.vehicle', verbose_name='Vehículo Asignado')),
                ('force', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.force', verbose_name='Fuerza')),
            ],
            options={
                'verbose_name': 'Agente',
                'verbose_name_plural': 'Agentes',
            },
        ),
    ]
