# Generated by Django 5.2.5 on 2025-08-29 11:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_hospital_agent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('kind', models.CharField(choices=[('comisaria', 'Comisaría'), ('cuartel', 'Cuartel de Bomberos'), ('base_transito', 'Base de Tránsito')], max_length=20, verbose_name='Tipo')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Dirección')),
                ('lat', models.FloatField(blank=True, null=True, verbose_name='Latitud')),
                ('lon', models.FloatField(blank=True, null=True, verbose_name='Longitud')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creado en')),
                ('force', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.force', verbose_name='Fuerza')),
            ],
            options={
                'verbose_name': 'Instalación',
                'verbose_name_plural': 'Instalaciones',
            },
        ),
    ]
