# Generated by Django 5.2.5 on 2025-08-29 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_facility'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='lat',
            field=models.FloatField(blank=True, null=True, verbose_name='Latitud'),
        ),
        migrations.AddField(
            model_name='agent',
            name='lon',
            field=models.FloatField(blank=True, null=True, verbose_name='Longitud'),
        ),
        migrations.AddField(
            model_name='hospital',
            name='lat',
            field=models.FloatField(blank=True, null=True, verbose_name='Latitud'),
        ),
        migrations.AddField(
            model_name='hospital',
            name='lon',
            field=models.FloatField(blank=True, null=True, verbose_name='Longitud'),
        ),
    ]
