# Generated by Django 5.2.5 on 2025-08-29 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_agent_lat_agent_lon_hospital_lat_hospital_lon'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='home_facility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.facility', verbose_name='Base'),
        ),
        migrations.AddField(
            model_name='agent',
            name='target_lat',
            field=models.FloatField(blank=True, null=True, verbose_name='Latitud Objetivo'),
        ),
        migrations.AddField(
            model_name='agent',
            name='target_lon',
            field=models.FloatField(blank=True, null=True, verbose_name='Longitud Objetivo'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='home_facility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.facility', verbose_name='Base'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='target_lat',
            field=models.FloatField(blank=True, null=True, verbose_name='Latitud Objetivo'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='target_lon',
            field=models.FloatField(blank=True, null=True, verbose_name='Longitud Objetivo'),
        ),
    ]
