# Generated by Django 5.2.5 on 2025-08-29 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_agent_home_facility_agent_target_lat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergency',
            name='ai_response',
            field=models.TextField(blank=True, verbose_name='Respuesta IA'),
        ),
    ]
