# Generated by Django 5.2.5 on 2025-08-29 19:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_emergency_ai_response'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalculatedRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_id', models.CharField(max_length=50, verbose_name='ID del Recurso')),
                ('resource_type', models.CharField(max_length=100, verbose_name='Tipo de Recurso')),
                ('distance_km', models.FloatField(verbose_name='Distancia (km)')),
                ('estimated_time_minutes', models.FloatField(verbose_name='Tiempo Estimado (min)')),
                ('priority_score', models.FloatField(verbose_name='Puntuación de Prioridad')),
                ('route_geometry', models.JSONField(verbose_name='Geometría de la Ruta')),
                ('status', models.CharField(choices=[('activa', 'Activa'), ('completada', 'Completada'), ('cancelada', 'Cancelada')], default='activa', max_length=20, verbose_name='Estado')),
                ('calculated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Calculado en')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completado en')),
                ('emergency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calculated_routes', to='core.emergency', verbose_name='Emergencia')),
            ],
            options={
                'verbose_name': 'Ruta Calculada',
                'verbose_name_plural': 'Rutas Calculadas',
                'ordering': ['priority_score', 'distance_km'],
            },
        ),
    ]
