# Generated by Django 5.2.6 on 2025-10-01 11:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_calculatedroute'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingSpot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=100, unique=True, verbose_name='ID Externo')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('spot_type', models.CharField(choices=[('street', 'Estacionamiento en Calle'), ('garage', 'Estacionamiento Cubierto'), ('lot', 'Playón de Estacionamiento'), ('emergency', 'Reservado para Emergencias')], default='street', max_length=20, verbose_name='Tipo')),
                ('lat', models.FloatField(verbose_name='Latitud')),
                ('lon', models.FloatField(verbose_name='Longitud')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Dirección')),
                ('total_spaces', models.PositiveIntegerField(default=1, verbose_name='Espacios Totales')),
                ('available_spaces', models.PositiveIntegerField(default=0, verbose_name='Espacios Disponibles')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Pago Requerido')),
                ('max_duration_hours', models.PositiveIntegerField(blank=True, null=True, verbose_name='Duración Máxima (horas)')),
                ('restrictions', models.JSONField(blank=True, null=True, verbose_name='Restricciones')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creado en')),
            ],
            options={
                'verbose_name': 'Lugar de Estacionamiento',
                'verbose_name_plural': 'Lugares de Estacionamiento',
                'indexes': [models.Index(fields=['is_active', 'lat', 'lon'], name='core_parkin_is_acti_9a025e_idx'), models.Index(fields=['available_spaces'], name='core_parkin_availab_3895ab_idx')],
            },
        ),
        migrations.CreateModel(
            name='StreetClosure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=100, unique=True, verbose_name='ID Externo')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre del Corte')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('closure_type', models.CharField(choices=[('total', 'Corte Total'), ('parcial', 'Corte Parcial'), ('alternado', 'Tránsito Alternado'), ('restringido', 'Tránsito Restringido')], default='total', max_length=20, verbose_name='Tipo de Corte')),
                ('lat', models.FloatField(verbose_name='Latitud')),
                ('lon', models.FloatField(verbose_name='Longitud')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Dirección')),
                ('geometry', models.JSONField(blank=True, null=True, verbose_name='Geometría GeoJSON')),
                ('start_date', models.DateTimeField(verbose_name='Fecha de Inicio')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Fin')),
                ('cause', models.CharField(blank=True, max_length=100, verbose_name='Causa')),
                ('affected_streets', models.JSONField(blank=True, null=True, verbose_name='Calles Afectadas')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creado en')),
            ],
            options={
                'verbose_name': 'Corte de Calle',
                'verbose_name_plural': 'Cortes de Calles',
                'ordering': ['-start_date'],
                'indexes': [models.Index(fields=['is_active', 'lat', 'lon'], name='core_street_is_acti_a3ecf7_idx'), models.Index(fields=['start_date', 'end_date'], name='core_street_start_d_01b558_idx')],
            },
        ),
        migrations.CreateModel(
            name='TrafficCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=100, unique=True, verbose_name='ID Externo')),
                ('location_name', models.CharField(max_length=255, verbose_name='Ubicación')),
                ('count_type', models.CharField(choices=[('vehicle', 'Conteo de Vehículos'), ('speed', 'Velocidad Promedio'), ('occupancy', 'Ocupación de Vía')], default='vehicle', max_length=20, verbose_name='Tipo de Conteo')),
                ('lat', models.FloatField(verbose_name='Latitud')),
                ('lon', models.FloatField(verbose_name='Longitud')),
                ('street_name', models.CharField(blank=True, max_length=255, verbose_name='Nombre de Calle')),
                ('count_value', models.PositiveIntegerField(verbose_name='Valor del Conteo')),
                ('unit', models.CharField(default='vehicles', max_length=50, verbose_name='Unidad')),
                ('timestamp', models.DateTimeField(verbose_name='Timestamp del Conteo')),
                ('period_minutes', models.PositiveIntegerField(default=60, verbose_name='Periodo en Minutos')),
                ('data_source', models.CharField(blank=True, max_length=100, verbose_name='Fuente de Datos')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creado en')),
            ],
            options={
                'verbose_name': 'Conteo de Tránsito',
                'verbose_name_plural': 'Conteos de Tránsito',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp', 'lat', 'lon'], name='core_traffi_timesta_3df795_idx'), models.Index(fields=['count_type', 'timestamp'], name='core_traffi_count_t_441878_idx')],
            },
        ),
        migrations.CreateModel(
            name='TransportAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=100, unique=True, verbose_name='ID Externo')),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('alert_type', models.CharField(choices=[('closure', 'Corte de Calle'), ('accident', 'Accidente'), ('construction', 'Obra'), ('event', 'Evento'), ('weather', 'Clima'), ('other', 'Otro')], default='other', max_length=20, verbose_name='Tipo de Alerta')),
                ('severity', models.CharField(choices=[('low', 'Baja'), ('medium', 'Media'), ('high', 'Alta'), ('critical', 'Crítica')], default='medium', max_length=20, verbose_name='Severidad')),
                ('lat', models.FloatField(blank=True, null=True, verbose_name='Latitud')),
                ('lon', models.FloatField(blank=True, null=True, verbose_name='Longitud')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Dirección')),
                ('start_date', models.DateTimeField(verbose_name='Fecha de Inicio')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Fin')),
                ('affected_routes', models.JSONField(blank=True, null=True, verbose_name='Rutas Afectadas')),
                ('recommended_actions', models.JSONField(blank=True, null=True, verbose_name='Acciones Recomendadas')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creado en')),
            ],
            options={
                'verbose_name': 'Alerta de Transporte',
                'verbose_name_plural': 'Alertas de Transporte',
                'ordering': ['-start_date'],
                'indexes': [models.Index(fields=['is_active', 'severity'], name='core_transp_is_acti_36551b_idx'), models.Index(fields=['alert_type', 'start_date'], name='core_transp_alert_t_79f950_idx')],
            },
        ),
    ]
