# Generated by Django 5.2.6 on 2025-10-01 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_parkingspot_streetclosure_trafficcount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencydispatch',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.agent', verbose_name='Agente'),
        ),
    ]
